const SET_CONVERSATION_NAME = "SET_CONVERSATION_NAME";
const RECEIVE_HSM_LIST = "RECEIVE_HSM_LIST";
const RECEIVE_AGENT_TAGS = "RECEIVE_AGENT_TAGS";
const RECEIVE_POLLS = "RECEIVE_POLLS";
const RECEIVE_HELPDESK_INTEGRATIONS = "RECEIVE_HELPDESK_INTEGRATIONS";
const RECEIVE_HUBSPOT_PROPERTIES = "RECEIVE_HUBSPOT_PROPERTIES";
const RECEIVE_CONVERSATION = "RECEIVE_CONVERSATION";
const RECEIVE_NODE_SELECTION = "RECEIVE_NODE_SELECTION";
const RECEIVE_GOOGLE_SHEET_CODE = "RECEIVE_GOOGLE_SHEET_CODE";
const SET_HAS_HUBSPOT_INTEGRATION = "SET_HAS_HUBSPOT_INTEGRATION";
const SET_COMPLETE_RECOMMENDATION_ACTION = "SET_COMPLETE_RECOMMENDATION_ACTION";
const SET_RECOMMENDATION_LEVEL = "SET_RECOMMENDATION_LEVEL";
const SET_RECOMMENDATION_SCORE = "SET_RECOMMENDATION_SCORE";
const SET_POLL_VISUALIZATION = "SET_POLL_VISUALIZATION";

export default {
  SET_CONVERSATION_NAME,
  RECEIVE_HSM_LIST,
  RECEIVE_AGENT_TAGS,
  RECEIVE_POLLS,
  RECEIVE_HELPDESK_INTEGRATIONS,
  RECEIVE_HUBSPOT_PROPERTIES,
  RECEIVE_CONVERSATION,
  RECEIVE_NODE_SELECTION,
  RECEIVE_GOOGLE_SHEET_CODE,
  SET_HAS_HUBSPOT_INTEGRATION,
  SET_COMPLETE_RECOMMENDATION_ACTION,
  SET_RECOMMENDATION_LEVEL,
  SET_RECOMMENDATION_SCORE,
  SET_POLL_VISUALIZATION
};
