const SET_ON_LOADING = "SET_ON_LOADING";
const DISABLE_DIAGRAM_SCROLL = "DISABLE_DIAGRAM_SCROLL";
const ENABLE_DIAGRAM_SCROLL = "ENABLE_DIAGRAM_SCROLL";

export default {
  SET_ON_LOADING,
  DISABLE_DIAGRAM_SCROLL,
  ENABLE_DIAGRAM_SCROLL,
};
