module.exports = {
  es: {
    noResults: "Oops! No hay resultados. 👀 Prueba con otro nombre",
    none: "Ninguna",
    yes: "Si",
    no: "No",
    cancel: "Cancelar",
    announcementModalImgName: "bg-client-success.svg",
    delete: "Eliminar",
    edit: "Editar",
    goalBlock: "Bloque objetivo",
    downloadCenter: "Centro de descargas",
    noReportsYet: "En este momento no tienes reportes generados",
    retryAllReports: "Reintentar todas las descargas fallidas",
    reportActions: "Acciones",
    generatedReports: "Reportes generados",
    selectAction: "Selecciona una acción a ejecutar",
    runAction: "Ejecutar acción ahora",
    actionRuning: "La acción se está ejecutando",
    searchReport: "Busca reporte por nombre o id...",
    downloadReport: "Descargar reporte",
    cancelDownload: "Cancelar descarga",
    globalReport: "Reporte global",
    summaryReport: "Reporte de resumen",
    responseblockReport: "Reporte bloque por bloque",
    responsetableReport: "Reporte de respuestas generales",
    versionshistorialReport: "Reporte Historial de versiones",
    generatedDate: "Generado el día",
    reportSuccessNotification:
      "Tu reporte se ha generado con éxito y está listo para la descarga -- Descargar ahora",
    reportErrorNotification:
      "Ha habido una falla en la generación de tu reporte -- Intenta de nuevo",
    reportProgressNotification:
      "⚡  Tu reporte se está generando y estará listo en 10 minutos",
    regenerateReport: "Volver a generar reporte",
    deleteAllReports: "Eliminar todas las descargas generadas",
    noSearchResults: "Oops! No hay resultados relacionados a tu búsqueda",
    generalReport: "Reporte general",
  },
  en: {
    noResults: "Oops! No results. 👀 Try another name",
    none: "None",
    yes: "Yes",
    no: "No",
    cancel: "Cancel",
    announcementModalImgName: "bg-client-success.svg",
    delete: "Delete",
    edit: "Edit",
    goalBlock: "Goal block",
    downloadCenter: "Download center",
    noReportsYet: "At this moment you do not have any generated reports",
    retryAllReports: "Retry all failed downloads",
    reportActions: "Actions",
    generatedReports: "Generated reports",
    selectAction: "Select an action to be performed",
    runAction: "Run action now",
    actionRuning: "Action is running",
    searchReport: "Search report by name or id...",
    downloadReport: "Download Report",
    cancelDownload: "Cancel download",
    globalReport: "Overall report",
    summaryReport: "Summary report",
    responseblockReport: "Block by block report",
    responsetableReport: "General response report",
    versionshistorialReport: "Version history report",
    generatedDate: "Generated on the day",
    reportSuccessNotification:
      "Your report has been successfully generated and is ready for download -- Download Now",
    reportErrorNotification:
      "There was an error generating your report Try again",
    reportProgressNotification:
      "⚡ Your report is being generated and will be ready in 10 minutes",
    regenerateReport: "Regenerate report",
    deleteAllReports: "Delete all generated downloads",
    noSearchResults: "Oops! There are no results related to your search",
    generalReport: "General report",
  },
  pr: {
    noResults: "Opa! Não há resultados. 👀 Tente outro nome",
    none: "Nenhum",
    yes: "Sim",
    no: "Não",
    cancel: "Cancelar",
    announcementModalImgName: "bg-client-success.svg",
    delete: "Remove",
    edit: "Editar",
    goalBlock: "Bloco objetivo",
    downloadCenter: "Centro de downloads",
    noReportsYet: "En este momento no tienes relatórios gerados",
    retryAllReports: "Tente novamente todos os downloads com falha",
    reportActions: "Ações",
    generatedReports: "Relatórios gerados",
    selectAction: "Selecionar uma ação para ejecutar",
    runAction: "Execute a ação agora",
    actionRuning: "A ação está em execução",
    searchReport: "Pesquisar relatório por nome ou por id...",
    downloadReport: "Baixar relatório",
    cancelDownload: "Cancelar download",
    globalReport: "Relatório geral",
    summaryReport: "relatório resumido",
    responseblockReport: "Relatório bloco a bloco",
    responsetableReport: "Relatório de resposta geral",
    versionshistorialReport: "Reporte Historial de versiones",
    generatedDate: "Gerado no dia",
    reportSuccessNotification:
      "Seu relatório foi gerado com sucesso e está pronto para download -- Faça o download agora",
    reportErrorNotification:
      "Ocorreu um erro ao gerar seu relatório -- Tente novamente",
    reportProgressNotification:
      "⚡ Seu relatório está sendo gerado e ficará pronto em 10 minutos",
    regenerateReport: "Regenerar relatório",
    deleteAllReports: "Excluir todos os downloads gerados",
    noSearchResults: "Ops! Nenhum resultado relacionado a tu búsqueda",
    generalReport: "Geral relatório",
  },
};
