const language = {
  es: {
    date: "Fecha",
    country_code: "Codigo de pais",
    questions: "Preguntas",
    cellphone: "Celular",
    status: "Estado",
    status_details: "Detalles del estado",
    deployment_status: "Estado del despliegue",
    conversation_stage: "Estado de la conversación",
    session_status: "Estado de la sesión",
    last_message: "Última actividad",
    deployment_timestamp: "Fecha del despliegue",
    delivered: "Entregado",
    ai: "En el flujo",
    human_handover: "En sesión con agentes",
    finished: "Sesión finalizada",
    not_finished: "En sesión",
    processing: "En proceso",
    sent: "Mensajes enviados",
    responded: "Respuestas",
    response_rate: "Tasa de respuesta",
    error: "Error",
    VALIDATION_ERROR: "Error de validación",
    REVOKED: "Despliegue cancelado",
    INVALID_PHONE: "Celular inválido",
    PUSH_NOTIFICATION: "Notificación",
    FAILURE_BY_HUMAN_HANDOVER: "Sesión activa en agentes",
    RECEIVED_BY_WORKER: "En proceso",
    RECEIVED: "Recibido",
    RETRY: "Volver a procesar",
    FAILURE_BY_RATE_LIMIT: "Falla con el límite de mensajes outboud por día",
    FAILURE: "Falla general",
    COMPANY_RATE_LIMIT: "Límite por compañia",
    FAILURE_BY_TIER_CAPACITY: "Peligro en calidad del tier",
    MISSING_PARAMETER: "Hubo un problema con algún parámetro",
    PARAMETER_MISMATCH: "Hubo un problema con algún parámetro",
    FAILURE_BY_OPTOUT_CONTACT: "Contacto en exclusión",
    INVALID_POLL: "Conversación eliminada/sobreescrita",
    CHARACTER_LIMIT_HEADER: "Encabezado demasiado largo debido a la variable",
    CHARACTER_LIMIT_BODY:
      "Cuerpo del mensaje demasiado largo debido a la variable",
    FAILURE_BY_DISABLED_HSM: "Error (HSM pausado)",
    FAILURE_BY_SPAM_RATE_LIMIT: "Error límite de spam",
    created_at: "Fecha de creación",
    total_users: "Total de usuarios",
    received: "Mensajes recibidos",
    average_per_day: "Promedio de mensajes recibidos por día",
    unique_users: "Total de usuarios únicos",
    human_sessions: "Transferido a un agente",
    response_date: "Fecha respuesta",
    actual_response: "Respuesta",
    question_text: "Pregunta",
    delivered_users: "Recibidos",
    not_responded: "No respondieron",
    answers: "Respondieron",
    target_event_type: "Tipo de objetivo",
    target_event_button_link: "Clic en botón con link",
    target_event_link: "Clic en link",
    target_event_read: "Usuarios que leyeron el mensaje",
    target_block_created: "Bloque objetivo creado",
    target_event_results: "Resultados",
    target_event_expectation: "Expectativa",
    option: "Opción",
  },
  en: {
    date: "Date",
    country_code: "Country code",
    questions: "Questions",
    cellphone: "Cellphone",
    status: "Status",
    status_details: "Status details",
    deployment_status: "Deployment status",
    conversation_stage: "Conversation stage",
    session_status: "Session status",
    last_message: "Last activity",
    deployment_timestamp: "Deployment date",
    ai: "In the flow",
    human_handover: "In session with agent",
    finished: "Session ended",
    not_finished: "In session",
    delivered: "Delivered",
    processing: "In process",
    sent: "Sent messages",
    responded: "Responses",
    response_rate: "Response rate",
    error: "Failed",
    VALIDATION_ERROR: "Validation error",
    REVOKED: "Deployment canceled",
    INVALID_PHONE: "Invalid cellphone",
    PUSH_NOTIFICATION: "Notification",
    FAILURE_BY_HUMAN_HANDOVER: "Active session in agents",
    RECEIVED_BY_WORKER: "In process",
    RECEIVED: "Received",
    RETRY: "Reprocess",
    FAILURE_BY_RATE_LIMIT: "Failure with limit of outboud messages per day",
    FAILURE: "General failure",
    COMPANY_RATE_LIMIT: "Limit per company",
    FAILURE_BY_TIER_CAPACITY: "Tier quality hazard",
    MISSING_PARAMETER: "There was a problem with some parameter",
    PARAMETER_MISMATCH: "There was a problem with some parameter",
    FAILURE_BY_OPTOUT_CONTACT: "Contact in exclusion",
    INVALID_POLL: "Deleted/overwritten poll",
    CHARACTER_LIMIT_HEADER: "Header too long because of variable",
    CHARACTER_LIMIT_BODY: "Body too long because of variable",
    FAILURE_BY_DISABLED_HSM: "Error (Paused HSM)",
    FAILURE_BY_SPAM_RATE_LIMIT: "Spam limit error",
    created_at: "Creation Date",
    total_users: "Total users",
    received: "Received messages",
    average_per_day: "Average messages received per day",
    unique_users: "Total Unique Users",
    human_sessions: "Transferred to an agent",
    response_date: "Responded at",
    actual_response: "Response",
    question_text: "Question",
    delivered_users: "Received",
    not_responded: "Not responded",
    answers: "They answered",
    target_event_type: "Goal Type",
    target_event_button_link: "Click on button with link",
    target_event_link: "Click link",
    target_event_read: "Users who read the message",
    target_block_created: "Goal block created",
    target_event_results: "Results",
    target_event_expectation: "Expectation",
    option: "Option",
  },
  pt: {
    date: "encontro",
    country_code: "Código do país",
    questions: "perguntas",
    cellphone: "Celular",
    status: "Doença",
    status_details: "Detalhes do estado",
    deployment_status: "status de implantação",
    conversation_stage: "Fase de conversa",
    session_status: "Estado da sessão",
    last_message: "ultima atividade",
    deployment_timestamp: "Data de implantação",
    ai: "No fluxo",
    human_handover: "Em sessão com agentes",
    finished: "Sessão encerrada",
    not_finished: "Sessão em processo",
    delivered: "Entregue",
    processing: "Em processo",
    sent: "Mensagens enviadas",
    responded: "Respostas",
    response_rate: "Taxa de resposta",
    error: "Falha",
    VALIDATION_ERROR: "Erro de validação",
    REVOKED: "Implementação cancelada",
    INVALID_PHONE: "Celular inválida",
    PUSH_NOTIFICATION: "Notificação",
    FAILURE_BY_HUMAN_HANDOVER: "Sessão ativa em agentes",
    RECEIVED_BY_WORKER: "Em processo",
    RECEIVED: "Recebido",
    RETRY: "Reprocessar",
    FAILURE_BY_RATE_LIMIT: "Falha com limite de mensagens outboud por dia",
    FAILURE: "Falha geral",
    COMPANY_RATE_LIMIT: "Limite por empresa",
    FAILURE_BY_TIER_CAPACITY: "Nível de risco de qualidade",
    MISSING_PARAMETER: "Houve um problema com algum parâmetro",
    PARAMETER_MISMATCH: "Houve um problema com algum parâmetro",
    FAILURE_BY_OPTOUT_CONTACT: "Contato em exclusão",
    INVALID_POLL: "Conversa excluída/substituída",
    CHARACTER_LIMIT_HEADER: "Cabeçalho muito longo por causa da variável",
    CHARACTER_LIMIT_BODY: "Corpo da mensagem muito longo por causa da variável",
    FAILURE_BY_DISABLED_HSM: "Erro (HSM pausado)",
    FAILURE_BY_SPAM_RATE_LIMIT: "Erro de limite de spam",
    created_at: "Data de criação",
    total_users: "Total de usuários",
    received: "Mensagens recebidas",
    average_per_day: "Média de mensagens recebidas por dia",
    unique_users: "Total de usuários únicos",
    human_sessions: "Transferido para humano",
    response_date: "Respondeu em",
    actual_response: "Resposta",
    question_text: "Pergunta",
    delivered_users: "Recebido",
    not_responded: "Não respondeu",
    answers: "Eles responderam",
    target_event_type: "Tipo de destino",
    target_event_button_link: "Clique no botão com link",
    target_event_link: "Clique no link",
    target_event_read: "Usuários que leem a mensagem",
    target_block_created: "Bloco de destino criado",
    target_event_results: "Resultados",
    target_event_expectation: "Expectativa",
    option: "opção",
  },
};

export default language;
