module.exports = {
  es: {
    googleTitle: "Integración con Google sheets",
    googleDes:
      "Envia las respuestas que dan tus usuarios en tiempo real a un documento de Google Sheets.",
    sheeturl: "URL de google sheets",
    intInfo: "¿Cómo funciona la integración?",
    clickHere: "Clic aquí",
    sheetsMsg: "Envía respuestas en tiempo real",
    loadingConv: "Estamos cargando tu conversación",
    read: "Leer",
    deliver: "Entregar",
    config: "Configuración de la pregunta",
    questionType: "Tipo de pregunta",
    open: "Abierta",
    closed: "Cerrada",
    message: "Mensaje",
    altFlux: "Flujo alterno",
    hideOpt: "Ocultar respuestas",
    variable: "Guardar respuesta",
    add: "Agregar",
    openQuestion: "Con respuesta abierta",
    closedQuestion: "Con opciones",
    withHsm: "Plantilla de mensaje (HSM)",
    openQuestionD: "Ideal para recolectar datos",
    closedQuestionD: "Diferentes caminos para elegir",
    closedQuestionButtons: "Con botones",
    closedQuestionButtonsD: "Hasta 3 botones de respuesta rápida",
    closedQuestionList: "Con lista de opciones",
    closedQuestionListD: "Hasta 10 opciones para elegir",
    withHsmD: "Mensajes aprobados por Facebook",
    humanChat: "Conversar con humano",
    humanChatD: "Toma el control de la conversación",
    connectConversation: "Conecta tu conversación a {{APPLICATION}}",
    linkConversation: "Enlace a conversación",
    linkConversationD: "Salto a conversaciones existentes",
    linkConversationLargeD:
      "¿Te gustaría llevar a tus usuarios a otra conversación? Interconecta conversaciones y crear nuevos caminos para tus usuarios usando el bloque de Enlace a conversación.",
    abTesting: "Pruebas A/B",
    abTestingD: "Dividir el flujo por porcentaje",
    abTestingLargeD:
      "Incluso los cambios más pequeños pueden incrementar la tasa de respuesta drásticamente. Con el bloque A/B testing, puedes probar diferentes copys o hasta imagenes para optimizar tus conversaciones.",
    conditionals: "Condiciones",
    conditionalsD: "Caminos a partir de datos",
    conditionalsLargeD:
      "Envía a tus usuarios por caminos distintos dependiedo de datos o parámetros configurables.",
    wantBlock: "¿Quieres incluir este tipo de bloque?",
    basicBlocks: "Bloques Básicos",
    advancedBlocks: "Bloques Avanzados",
    blockType: "Tipo de bloque",
    integrations: "Integraciones",
    sendEmail: "Enviar email",
    sendEmailD: "A tu equipo o usuarios",
    sendEmailLargeD:
      "Toma acciones rápidas. Envía un correo a tu equipo o a tus usuarios a partir de las respuestas de tus conversaciones en treble.ai.",
    createAndUpdate: "Crea y actualiza datos en {{CRM}}",
    connectTrebleWith: "Conecta treble.ai con {{APPLICATION}}",
    custom: "Personalizada",
    customD: "¿Te gustaría tener otra integración?",
    noHsm:
      "Por favor asegurate de tener la palabra bien escrita o intenta cambiando tu busqueda",
    save: "Guardar como copia",
    reWrite: "Sobreescribir",
    create: "Crear",
    savebtn: "Guardar",
    convName: "Sin nombre",
    noResults: "Sin resultados",
    continueAgents: "Continuar en {{AGENTS}}",
    agentType: "Tipo de agente",
    helpdeskLargeD:
      "Crea tickets y permite a tus agentes tener control de las conversaciones en {{HELPDESK}} a partir de las respuestas de tus conversaciones en treble.ai. Soluciona rápidamente y brinda la mejor atención a tus usuarios.",
    helpdeskEmail: "Tu email de {{HELPDESK}} para permisos de administrador",
    helpdeskPhoneProperty:
      "Propiedad de {{HELPDESK}} en donde almacenas los celulares de tus usuarios",
    helpdeskAdminAccess:
      "Un administrador debe permitir el acceso de treble.ai a {{HELPDESK}}",
    installHelpdeskApp: "Instala la aplicación de treble.ai en {{HELPDESK}}",
    installZendeskApiKeyHelp: "Allí deberás ingresar tu API key de treble.ai",
    installHere: "Instala aquí",
    allowAccess: "Permitir acceso",
    hubspotEmailD:
      "El email tendrá permisos de administrador dentro de la integración de HubSpot <> treble.ai para administrar otros agentes y etiquetas",
    hubspotExtension: "Instala la extensión de Google Chrome de treble.ai",
    hubspotExtensionD:
      "En la página de configuración, encontrarás un enlace para instalar la extensión de Google Chrome y el código de activación utilizado para vincular la extensión con Treble. Todas las personas que van a responder mensajes de WhatsApp desde HubSpot deben realizar este proceso",
    goToTrebleSettings: "Ir a la configuración de Treble",
    crmLargeD:
      "Envía respuestas de treble.ai a {{CRM}} para crear nuevos contactos o actualizar sus datos. También puedes desplegar campañas de treble.ai a tus contactos desde {{CRM}}",
    autoWorkflowsLargeD:
      "Conecta fácilmente los datos que recopiles en treble.ai con las aplicaciones que usas en tu día a día con la integración rápida de {{APPLICATION}}.",
    hubspotReceiveEmail: "¿Quién va a recibir esta conversación?",
    noStartFound: "No es posible encontrar un comienzo",
    cancel: "Cancelar",
    successRequestSent: "¡Solicitud enviada! Pronto te contactaremos",
    requestIntegration: "Solicitar integración",
    requestNewIntegration: "Solicitar nueva integración",
    whichApplication: "¿Cuál aplicación te gustaría integrar?",
    applicationName: "Nombre de la aplicación",
    useCase: "Caso de uso",
    requestNewIntegrationD:
      "Describe brevemente el caso de uso que te gustaría que estuviera disponible con esta integración",
    completeField: "Debes completar este campo",
    wantIt: "Quiero tenerlo",
    integrationWith: "Integración con {{APPLICATION}}",
    includeIntegration: "¿Quieres incluir esta integración?",
    hubspotModalTitle: "Conecta tu cuenta a HubSpot",
    hubspotAccess:
      "Con esta integración autorizas el envió de conversaciones desde HubSpot por medio de treble.ai y acceso a la información de tus contactos para el mismo uso",
    account: "Cuenta",
    connect: "Conectar",
    successHubSpotConnect: "¡Has conectado HubSpot de manera exitosa!",
    waitingHubSpotConnect: "Estamos conectándote con HubSpot",
    input: "Busca o crea una nueva variable",
    successRequest: "¡Solicitud enviada! Pronto te contactaremos",
    sheetsLoad: "Revisando los permisos y formato en google sheets",
    sheetsSuccess: "!Permisos y formato correctos!",
    sheetsNoPermissions: "No tienes los permisos correctos en google sheets",
    sheetsNoHeaders:
      "El archivo debe contener country_code y cellphone en columnas separadas en la primera fila",
    sheetsInclude:
      "¡Incluíste un archivo de google sheets! Recuerda tener el link público y con permisos de editor",
    sheetsProblem: "Encontramos un problema con su archivo de google sheets",
    atention: "¡Atención!",
    helpdeskModalTitle: "Conecta tu cuenta con {{HELPDESK}}",
    helpdeskAccess:
      "Con esta integración autorizas el envió de conversaciones desde {{HELPDESK}} por medio de treble.ai y acceso a la información de tus contactos para el mismo uso",
    helpdeskHost: "Dominio",
    successHelpdeskConnect:
      "¡Ya está conectado tu dasboard de {{HELPDESK}} con treble.ai!",
    helpdeskAPIKey: "API key de un administrador",
    helpdeskCompanyId: "Identificador de tu compañía dentro de {{HELPDESK}}",
    waitingHelpdeskConnect: "Estamos conectándote con {{HELPDESK}}",
    noIntegration: "Parece que ya tienes una integración que no es con ",
    openQuestionType: "Abierta",
    closedQuestionType: "Cerrada",
    closedQuestionButtonsType: "Cerrada con botones",
    closedQuestionListType: "Cerrada en lista",
    equals: "igual a",
    greater: "mayor a",
    less: "menor a",
    greaterEqual: "mayor o igual a",
    lessEqual: "menor o igual a",
    different: "diferente a",
    contains: "contiene",
    notContains: "no contiene",
    addCondition: "AGREGAR CONDICIÓN",
    stablishConditions: "Establece condiciones",
    configuration: "Configuración",
    name: "Nombre",
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    portuguese: "Portugués",
    french: "Francés",
    italian: "Italiano",
    limitMessagesAndTimer: "Temporizador y límite de mensajes",
    noMessageLimit: "Sin límites",
    messageLimit: "Número de mensajes",
    messageLimitDescription:
      "Limita la cantidad de respuestas que puede enviar un usuario antes de continuar el flujo",
    exactNumber: "Número exacto",
    timer: "Temporizador",
    timerDescription:
      "Determina un tiempo para que el usuario pueda responder antes de continuar con el flujo",
    seconds: "Segundos",
    minutes: "Minutos",
    saveOnVariableDescription:
      "Almacena la respuesta de tu usuario como una variable según tipo de mensaje (texto, imagen, documento etc.)",
    typeOfVariable: "Tipo de respuesta",
    nameOfVariable: "Nombre de la variable",
    allVarTypes: "Todos los tipos",
    textVarType: "Texto",
    imageVarType: "Imagen",
    videoVarType: "Video",
    audioVarType: "Audio",
    documentVarType: "Archivo",
    locationVarType: "Ubicación",
    stickerVarType: "Sticker",
    numericVarType: "Número",
    emailVarType: "Email",
    zipcodeVarType: "Código postal",
    contactsVarType: "Contacto",
    noStart: "No se puedo encontrar un inicio de la conversación",
    selectPoll: "Seleccionar conversación",
    redirectPollD:
      "Redirecciona a tus usuarios a la otras conversaciones enlazando flujos dentro de un mismo creador",
    searchPoll: "Busca tu conversación por nombre o ID",
    new: "NUEVO",
    noPollRed: "Una de las conversaciones con redirección ha sido eliminada.",
    autoMsgPA: "¿Sigues ahí?",
    autoMsg: "Mensaje del reintento automático",
    autoTime: "Tiempo del reintento automático",
    autoTitle: "Reintento automático",
    customAns: "Personalice sus respuestas como opción de exclusión",
    optWeb: "Establecer un webhook de exclusión voluntaria",
    sheetsVariable: "Variable mensaje inbound",
    sheetsVariablePH: "Nombre de la variable en tu sheets",
    alternateFlowError:
      "Oops! Hay bloques que están conectados de tal forma que vas a enviar infinitos mensajes si no responden. Revisa tu conversación",
    nodeErrors:
      "Hay algún problema con las preguntas resaltadas. Por favor revisa estas preguntas",
    helpdeskAction: "Acción en CRM",
    helpdeskActionD: "Guarda valores en Hubspot",
    customCondition: "⚙️ Condición personalizada",
    timeCondition: "⏰ Condición horaria",
    timezone: "Huso horario",
    timezonePH: "Elige un huso horario",
    timezoneSearch: "Busca un huso horario",
    to: "hasta",
    between: "entre",
    selectTimezone:
      "Establece el huso horario desde el apartado de configuración",
    overwriteConfirmationTitle: "¿Sobrescribir conversación?",
    overwriteConfirmation1:
      "Sobrescribir la conversación tiene algunas implicaciones",
    overwriteConfirmation2:
      "Cualquier sesión activa que los usuarios tengan con esta conversación se cerrará si no están hablando con un agente",
    overwriteConfirmation3:
      "Se creará una nueva versión de esta conversación. Si desea consultar los resultados anteriores en la sección de estadísticas, asegúrese de seleccionar la versión correcta",
    askTwilioListContentSid:
      "Por favor ingresa el Content Sid de tu mensaje de tipo twilio/list-picker.",
    helpdeskTicket: "Creación de tickets",
    helpdeskTicketD: "Crea tickets en Hubspot",
    NoResultsFound: "Oops! No hay resultados. 👀 Prueba con otro nombre",
    hubspotV1Error: "Elimina todos los nodos de HubSpot V1 antes de continuar",
    hubspotV1Deprecated: "HubSpot V1 ya no es soportado",
    hubspotV1DeprecatedD:
      "La versión 1 de agentes de HubSpot ya no es soportada por treble. Por favor elimina este nodo si deseas guardar esta conversación",
    modalErrorTitle: "Error en la conexión con hubspot",
    modalErrorBody:
      "No se han logrado sincronizar las funcionalidades y variables de HubSpot en esta conversación (Esto no afectará a tu operación). Para editar y agregar acciones de HubSpot es necesario volver a cargar la página",
    continueToEditor: "Continuar al editor",
    tryAgain: "Volver a intentar",
    hsmPH: "Buscar por nombre de plantilla HSM...",
    hsmPaused: "HSM en pausa",
    hsmPausedText:
      "Actualmente esta plantilla HSM ha alcanzado la calificación de calidad más baja (rojo) y se encuentra inhabilitada. Meta pausa de manera automática todas las plantillas que hayan alcanzado esta instancia para proteger la calificación de calidad del número de teléfono. Para mayor información puedes acceder a:",
    optoutWarningTitle: "Estás a punto de utilizar una opción Optout",
    optoutWarningText:
      "Recuerda que al colocar una opción como optout estás aceptando que no podrás volver a contactar a todos los usuarios que la seleccionen. (Treble.ai tampoco podrá contactarlos)",
    optoutWarningButton: "Acepto los términos de la opción optout",
    optoutWarningheader: "🚨 😱 ⚠️",
    tipsMenuTitle: "Biblioteca de tips",
    curiositytitle: "🤔 Despierta la curiosidad",
    optouttitle: "🥶 Usa la opción Opt-out",
    imagestitle: "👀 Agrega imágenes",
    shorttitle: "👌 Crea flujos cortos",
    tonetitle: "😁 Emplea el tono de tu marca",
    optionstitle: "📗 Utiliza bloques con opciones",
    targettitle: "🎯 Coloca tu objetivo al inicio",
    abtestingtitle: "😉 Realiza pruebas A/B",
    curiositymainInfo:
      "La calidad de tu conversación puede mejorar si logras despertar la curiosidad de tus usuarios.",
    optoutmainInfo:
      "Al activar esta opción permites a tus usuarios elegir si es que ya no desean seguir recibiendo mensajes que les envíes.",
    imagesmainInfo:
      "Agregar imágenes ayuda a que el contenido de tus mensajes sea más atractivo, pero ¡Ten cuidado! Si agregas demasiadas imágenes en tus conversaciones puedes confundir a tus usuarios.",
    shortmainInfo:
      "Sabemos que esto no aplica para todos los casos, sin embago, considera que los flujos cortos pueden ayudarte a que la conversación que mantengas con tus usuarios sea más fácil y llevadera.\n\nUn flujo corto puede ser considerado aquel que tenga máximo 10 bloques.",
    tonemainInfo:
      "Definir y emplear la voz de tu marca en las conversaciones ayudará a que conectes mejor con tus usuarios.\n\nSi empleas la voz de tu marca de manera efectiva lograrás que tus usuarios estén más enganchados con todo el contenido que les envíes.",
    optionsmainInfo:
      "Siempre será más sencillo para tus usuarios tomar una decisión para continuar en el flujo si les muestras un listado de opciones.",
    targetmainInfo:
      "Sabemos que esto no aplica para todos los casos, sin embago, considera que colocar tu objetivo cercano al inicio del flujo incrementa las posibilidades de que se cumpla.",
    abtestingmainInfo:
      "Una buena práctica es utilizar el bloque de pruebas A/B. El beneficio principal de esta funcionalidad es que te ayuda a entender mejor el comportamiento de tus usuarios.\n\nEntender a qué tipo de contenido visual son más afines o cuáles son los textos que funcionan mejor para tu audiencia es crucial para mejorar la calidad de las campañas que ejecutes en el futuro.",
    example: "Ejemplo:",
    benefits: "Beneficios:",
    optoutOption1:
      "Mantienes tu base de usuarios depurada por lo que la efectividad de tus campañas puede ser mayor al ya no enviar mensajes a usuarios que no desean recibir tu contenido.",
    optoutOption2:
      "La calidad de tu línea no se ve afectada: Recuerda que si no activas esta opción, los usuarios que no deseen recibir tu contenido pueden bloquear y denunciar tu línea desde WhatsApp, afectando así, la calidad de la misma.",
    howToActivate: "¿Cómo activar esta opción?",
    BUTTONS_BLOCKtitle: "Utiliza Bloques con botones",
    BUTTONS_BLOCKtext:
      "Los usuarios avanzan con mayor facilidad en una conversación con botones.",
    BUTTONS_BLOCKbuttonText: "Agregar bloque con botones",
    GOAL_BLOCKtitle: "Define un bloque objetivo",
    GOAL_BLOCKtext:
      "Medir los objetivos de tus campañas te ayudará a tomar mejores decisiones.",
    GOAL_BLOCKbuttonText: "Define objetivo en tu HSM",
    TWO_BLOCK_MINIMUMtitle: "Mínimo crea 2 bloques",
    TWO_BLOCK_MINIMUMtext:
      "Aunque todo pueda incluirse en el HSM, opta mejor por interactuar con tus usuarios.",
    TWO_BLOCK_MINIMUMbuttonText: "Agregar bloque con respuesta abierta",
    EMOJIStitle: "Utiliza Emojis",
    EMOJIStext:
      "Los emojis transmiten emociones y esto hace que tus mensajes tengan mayor relevancia.",
    EMOJISbuttonText: "Agregar bloque con emojis más usados",
    NOT_INCLUDED_ANSWERtitle: "Respuesta no incluída en opciones",
    NOT_INCLUDED_ANSWERtext:
      "Si un usuario responde algo distinto al listado de opciones/botones, puedes redirigirlo a un nuevo bloque en la conversación o simplemnte enviarle un mensaje personalizado para que seleccione una de las opciones predeterminadas.",
    SHORT_TEXTtitle: "Coloca textos cortos",
    SHORT_TEXTtext:
      "Sabemos que esto no aplica para todos los casos, sin embago, considera que las personas van a destinar un tiempo determinado a leer tus mensajes, mientras más concretos sean, mejor.",
    automaticImprovementTitle: "Mejora automática ⚡",
    automaticImprovementText:
      "Agregaremos bloques y funcionalidades a tu flujo de manera automática acorde a lo siguiente:",
    automaticImprovement1: "- Bloque Objetivo en HSM",
    automaticImprovement2: "- Bloque con botones",
    automaticImprovement3: "- Bloque con Emojis más utilizados",
    automaticImprovementButtonText: "Aceptar y continuar",
    questionEmojis:
      "Estos son los Emojis más utilizados: (Copia y pega en donde desees) 😃 🙂 😋 😍 🤑 😎 🥳 🤫 🤔 🤗 😱 🤩 🤯 👋 👍 👌👇 👉 🙏 💪 ✨ 🔥 🍪 🚨 🚀 💰 🎉 📚 📍 🔍 🥁 👯 ‍️💎 ✅ ❗ 💯 📢 🔔 🕒 ⏰ 💲 🎁 💡 🛎 🎀",
    conversationQuality: "Calidad de la conversación",
    score: "Puntos",
    automaticImprovement: "Mejora automática",
    knowMoreTips: "Conoce más tips",
    knowMore: "Conoce más",
    normal: "Normal",
    advanced: "Avanzado",
    recommendationLevel: "Profundidad de análisis",
    minimize: "Minimizar",
    conversationQualityText1:
      "La calidad de la conversación hace referencia al uso de buenas prácticas en tus campañas.",
    conversationQualityText2:
      "En Treble.ai analizamos los datos de las mejores campañas que se han desplegado y estamos seguros de que estos insights harán tus conversaciones más efectivas.",
    evaluationTooBig:
      "Análisis no disponible para conversaciones de más de 100 bloques 😨",
    errorSavingConversation:
      "Error al guardar la conversación. Contact a soporte por favor.",
    errorCreatingConversation:
      "Error al crear la conversación. Contact a soporte por favor.",
    loadingConversation: "Los cambios se están guardando, espera un momento...",
    understood: "Entendido",
    GOAL_BLOCKmustHave:
      "Para guardar o sobrescribir esta conversación es necesario agregar un bloque objetivo",
    publish: "Publicar",
    publishNewConvTitle: "Publicar nueva versión de la conversación",
    publishConvSub:
      "Antes de publicar una nueva versión de la conversación considera las siguientes implicaciones:",
    publishItem1:
      "Cualquier sesión activa que los usuarios tengan con esta conversación se cerrará si no están hablando con un agente.",
    publishItem2:
      "Para consultar los resultados de versiones anteriores en la sección de estadísticas, debes asegúrate de seleccionar la versión correcta.",
    undo: "Deshacer",
    redo: "Rehacer",
    currentPublishedConv: "Versión publicada:",
    synctool: "Cambios guardados",
    noDrafttool: "Sin sincronizar",
    notSynctool: "Sin sincronizar",
    syncErrortool: "Revisa tu conexión",
    noPublishTool1:
      "Para que la conversación se guarde junto con todos los cambios que realices, debes ",
    noPublishTool2: " al menos una versión. 👌",
    noPublishedVersion: "Ninguna versión publicada",
    noChangesApply:
      "Estás viendo la versión publicada de esta conversación, por lo que ningún cambio que hagas aquí se guardará.",
    continueEditing: "Salir para seguir editando",
    publishedVersion: "Vista de versión publicada",
    firstLoad: "La conversación se está cargando, espera un momento...",
    changeVisualization:
      "Se está cambiando de visualización, esto puede tomar un momento...",
    conversationsTemplatesModalText:
      "👉 Conoce los flujos que generan mayor conversión 💥",
    conversationsTemplatesModalButton1: "Conocer flujos",
    conversationsTemplatesModalButton2: "No me interesa",
  },
  en: {
    googleTitle: "Integration with Google sheets",
    googleDes:
      "Send the responses that your users give in real time to a Google Sheets document.",
    sheeturl: "google sheets url",
    intInfo: "How does the integration work?",
    clickHere: "Click here",
    sheetsMsg: "Send responses in real time",
    loadingConv: "We are loading your conversation",
    read: "Read",
    deliver: "Deliver",
    config: "Question settings",
    questionType: "Question type",
    open: "Open",
    closed: "Closed",
    message: "Message",
    altFlux: "Alternate flow",
    hideOpt: "Hide responses",
    variable: "Save response as variable",
    add: "Add",
    openQuestion: "With open answer",
    closedQuestion: "With options",
    withHsm: "Message template (HSM)",
    openQuestionD: "Ideal for collecting data",
    closedQuestionD: "Different paths to choose",
    closedQuestionButtons: "With list of buttons",
    closedQuestionButtonsD: "Up to 3 quick reply buttons",
    closedQuestionList: "With a list of options",
    closedQuestionListD: "Up to 10 list options for selection",
    withHsmD: "Facebook Approved Messages",
    humanChat: "Chat with human",
    humanChatD: "Take control of the conversation",
    connectConversation: "Connect your conversation to {{APPLICATION}}",
    linkConversation: "Link to conversation",
    linkConversationD: "Jump to existing conversations",
    linkConversationLargeD:
      "Would you like to take your users to another conversation? Interconnect conversations and create new paths for your users using the Link to conversation block.",
    abTesting: "A/B testing",
    abTestingD: "Divide the flow by percentage",
    abTestingLargeD:
      "Even the smallest changes can dramatically increase the response rate. With the A/B testing block, you can test different copies or even images to optimize your conversations.",
    conditionals: "Conditions",
    conditionalsD: "Paths from data",
    conditionalsLargeD:
      "Send your users different ways depending on data or configurable parameters.",
    wantBlock: "Do you want to include this type of block?",
    createAndUpdate: "Create and update data in {{CRM}}",
    connectTrebleWith: "Connect treble.ai with {{APPLICATION}}",
    basicBlocks: "Basic Blocks",
    advancedBlocks: "Advanced Blocks",
    blockType: "Block type",
    integrations: "Integrations",
    sendEmail: "Send email",
    sendEmailD: "To your team or users",
    sendEmailLargeD:
      "Take quick action. Send an email to your team or your users from the responses of your conversations on treble.ai.",
    custom: "Custom",
    customD: "Would you like to have another integration?",
    noHsm:
      "Please make sure you have the word spelled correctly or try changing your search",
    save: "Save as copy",
    reWrite: "Overwrite",
    create: "Create",
    savebtn: "Save",
    convName: "Without name",
    noResults: "No results",
    continueAgents: "Continue on {{AGENTS}}",
    agentType: "Agent type",
    helpdeskLargeD:
      "Create tickets and allow your agents to have control of the conversations in {{HELPDESK}} from the responses of your conversations in treble.ai. Solve quickly and provide the best service to your users.",
    helpdeskEmail: "Your {{HELPDESK}} email for admin permissions",
    helpdeskAdminAccess:
      "An administrator must allow treble.ai access to {{HELPDESK}}",
    installHelpdeskApp: "Install the treble.ai {{HELPDESK}} App",
    installZendeskApiKeyHelp: "There you must input your API key of treble.ai",
    helpdeskPhoneProperty:
      "{{HELPDESK}} property where you store your users' cellphones",
    installHere: "Install here",
    allowAccess: "Allow access",
    hubspotEmailD:
      "The email will have admin permissions inside the HubSpot <> treble.ai integration to manage other agents and tags",
    hubspotExtension: "Install the Google Chrome extension from treble.ai",
    hubspotExtensionD:
      "At the settings page you will find a link to install the Google Chrome extension and the activation code used to link the extension with Treble. Every person who is going to respond WhatsApp messages from HubSpot needs to do this process",
    goToTrebleSettings: "Go to Treble settings",
    crmLargeD:
      "Send treble.ai responses to {{CRM}} to create new contacts or update your details. You can also deploy treble.ai campaigns to your contacts from {{CRM}}",
    autoWorkflowsLargeD:
      "Easily connect the data you collect in treble.ai with the applications you use in your day-to-day with {{APPLICATION}}'s fast integration.",
    hubspotReceiveEmail: "Who is going to receive this conversation?",
    noStartFound: "Can't find a start",
    cancel: "Cancel",
    successRequestSent: "Request sent! We will contact you soon",
    requestIntegration: "Request integration",
    requestNewIntegration: "Request new integration",
    whichApplication: "Which application would you like to integrate?",
    applicationName: "Application name",
    useCase: "Case of use",
    requestNewIntegrationD:
      "Briefly describe the use case you would like to have available with this integration",
    completeField: "Please complete this field",
    wantIt: "I want it",
    integrationWith: "Integration with {{APPLICATION}}",
    includeIntegration: "Do you want to include this integration?",
    hubspotModalTitle: "Connect your account to HubSpot",
    hubspotAccess:
      "With this integration you authorize the sending of conversations from HubSpot through treble.ai and access to the information of your contacts for the same purpose",
    account: "Account",
    connect: "Connect",
    successHubSpotConnect: "You have successfully connected HubSpot!",
    waitingHubSpotConnect: "We are connecting you with HubSpot",
    input: "Search or create a new variable",
    successRequest: "Request sent! We will contact you soon",
    sheetsLoad: "Checking the permissions and format in google sheets",
    sheetsSuccess: "Correct format and permissions!",
    sheetsNoPermissions:
      "You don't have the correct permissions on google sheets",
    sheetsNoHeaders:
      "The file must contain country_code and cellphone in separate columns in the first row",
    sheetsInclude:
      "You included a google sheets file! Remember to have the public link and with publisher permission",
    sheetsProblem: "We found a problem with your google sheets file",
    atention: "Attention!",
    helpdeskModalTitle: "Connect your account with {{HELPDESK}}",
    helpdeskAccess:
      "With this integration you authorize the sending of conversations from {{HELPDESK}} through treble.ai and access to the information of your contacts for the same purpose",
    helpdeskHost: "Domain",
    successHelpdeskConnect:
      "Your {{HELPDESK}} dasboard is now connected to treble.ai!",
    helpdeskAPIKey: "API key from an administrator",
    helpdeskCompanyId: "Identifier of your company inside {{HELPDESK}}",
    waitingHelpdeskConnect: "We are connecting you with {{HELPDESK}}",
    noIntegration: "You already have an integration that does not match ",
    openQuestionType: "Open",
    closedQuestionType: "Closed",
    closedQuestionButtonsType: "Closed with buttons",
    closedQuestionListType: "Closed inside list",
    equals: "equals",
    greater: "greater than",
    less: "less than",
    greaterEqual: "greater than or equal",
    lessEqual: "less than or equal",
    different: "different from",
    contains: "contains",
    notContains: "doesn't contain",
    addCondition: "ADD CONDITION",
    stablishConditions: "Stablish conditions",
    configuration: "Configuration",
    name: "Name",
    language: "Language",
    spanish: "Spanish",
    english: "English",
    portuguese: "Portuguese",
    french: "French",
    italian: "Italian",
    limitMessagesAndTimer: "Timer and message limit",
    noMessageLimit: "Unlimited",
    messageLimit: "Number of messages",
    messageLimitDescription:
      "Limits the number of responses a user can send before continuing the flow",
    exactNumber: "Exact number",
    timer: "Timer",
    timerDescription:
      "Determine a time for the user to respond before continuing with the flow",
    seconds: "Seconds",
    minutes: "Minutes",
    saveOnVariableDescription:
      "Store your user's response as a variable according to the type of message (text, image, document, etc.)",
    typeOfVariable: "Type of answer",
    nameOfVariable: "Name of the variable",
    allVarTypes: "All types",
    textVarType: "Text",
    imageVarType: "Image",
    videoVarType: "Video",
    audioVarType: "Audio",
    documentVarType: "File",
    locationVarType: "Location",
    stickerVarType: "Sticker",
    numericVarType: "Number",
    emailVarType: "Email",
    zipcodeVarType: "Zip code",
    contactsVarType: "Contact",
    noStart: "Can't find a conversation start",
    selectPoll: "Select conversation",
    redirectPollD:
      "Redirect your users to other conversations by linking conversations within the same creator",
    searchPoll: "Search your conversation by name or ID",
    new: "NEW",
    noPollRed: "One of the redirected conversations has been deleted.",
    autoMsgPA: "Are you still there?",
    autoMsg: "Automatic retry message",
    autoTime: "Automatic retry time",
    autoTitle: "Automatic retry",
    customAns: "Customize your answers as an opt-out",
    optWeb: "Set an opt-out webhook",
    sheetsVariable: "Inbound message variable",
    sheetsVariablePH: "Name of the variable in your sheet",
    alternateFlowError:
      "Oops! There are blocks that are connected in such a way that you will send infinite messages if they do not respond. Check your conversation",
    nodeErrors:
      "There is something wrong with the highlighted questions. Please review these questions",
    helpdeskAction: "CRM Action",
    helpdeskActionD: "Save values in Hubspot",
    customCondition: "⚙️ Custom condition",
    timeCondition: "⏰ Time condition",
    timezone: "Time zone",
    timezonePH: "Choose a time zone",
    timezoneSearch: "Search for a time zone",
    to: "to",
    between: "between",
    selectTimezone: "Set your time zone from the configuration section",
    overwriteConfirmationTitle: "Overwrite conversation?",
    overwriteConfirmation1:
      "Overwriting the conversation has some implications",
    overwriteConfirmation2:
      "Any active sessions users have with this conversation will be closed if they aren't talking with an agent",
    overwriteConfirmation3:
      "A new version of this conversation will be created. If you want to check previous results in the statistics section make sure to select the correct version",
    askTwilioListContentSid:
      "Please enter the Content Sid of your twilio/list-picker type message.",
    helpdeskTicket: "Ticket creation",
    helpdeskTicketD: "Create tickets in Hubspot",
    NoResultsFound: "Oops, no results. 👀 Try another name",
    hubspotV1Error: "Please delete all HubSpot V1 nodes before continuing",
    hubspotV1Deprecated: "HubSpot V1 is no longer supported",
    hubspotV1DeprecatedD:
      "HubSpot agents version 1 is no longer supported by treble. Please remove this node if you wish to save this conversation",
    modalErrorTitle: "Error connecting to hubspot",
    modalErrorBody:
      "Failed to sync HubSpot features and variables in this conversation (This will not affect your operation). Editing and adding HubSpot actions requires a reload of the page",
    continueToEditor: "Continue to editor",
    tryAgain: "Try Again",
    hsmPH: "Search by HSM template name...",
    hsmPaused: "HSM paused",
    hsmPausedText:
      "Currently this HSM template has reached the lowest quality rating (red) and is disabled. Meta automatically pauses all templates that have reached this instance to protect the phone number quality rating. For more information you can access:",
    optoutWarningTitle: "Estás a punto de utilizar una opción Optout",
    optoutWarningText:
      "Recuerda que al colocar una opción como optout estás aceptando que no podrás volver a contactar a todos los usuarios que la seleccionen. (Treble.ai tampoco podrá contactarlos)",
    optoutWarningButton: "Acepto los términos de la opción optout",
    optoutWarningheader: "🚨 😱 ⚠️",
    tipsMenuTitle: "Tip library",
    curiositytitle: "🤔 Awaken curiosity",
    optouttitle: "🥶 Use the Opt-out option",
    imagestitle: "👀 Add images",
    shorttitle: "👌 Create short flows",
    tonetitle: "😁 Use your brand tone",
    optionstitle: "📗 Use blocks with options",
    targettitle: "🎯 Put your goal at the beginning",
    abtestingtitle: "😉 Perform A/B tests",
    curiositymainInfo:
      "The quality of your conversation can improve if you manage to arouse the curiosity of your users.",
    optoutmainInfo:
      "By activating this option you allow your users to choose if they no longer wish to receive messages that you send them.",
    imagesmainInfo:
      "Adding images helps make the content of your messages more attractive, but be careful! If you add too many images in your conversations you can confuse your users.",
    shortmainInfo:
      "We know that this does not apply to all cases, however, consider that short flows can help you make the conversation you have with your users easier and more bearable.\n\nA short flow can be considered one that has a maximum of 10 blocks.",
    tonemainInfo:
      "Defining and using your brand's voice in conversations will help you connect better with your users.\n\nIf you use the voice of your brand effectively, you will make your users more engaged with all the content you send them.",
    optionsmainInfo:
      "It will always be easier for your users to make a decision to continue in the flow if you show them a list of options.",
    targetmainInfo:
      "We know that this does not apply to all cases, however, consider that placing your objective close to the beginning of the flow increases the chances that it will be fulfilled.",
    abtestingmainInfo:
      "A good practice is to use block A/B testing. The main benefit of this functionality is that it helps you better understand the behavior of your users.\n\nUnderstanding what type of visual content they are most akin to or what texts work best for your audience is crucial to improving the quality of the campaigns you run in the future.",
    example: "Example:",
    benefits: "Benefits:",
    optoutOption1:
      "You keep your user base refined so that the effectiveness of your campaigns can be greater by no longer sending messages to users who do not wish to receive your content.",
    optoutOption2:
      "The quality of your line is not affected: Remember that if you do not activate this option, users who do not wish to receive your content can block and report your line from WhatsApp, thus affecting its quality.",
    howToActivate: "How to activate this option?",
    BUTTONS_BLOCKtitle: "Use Blocks with buttons",
    BUTTONS_BLOCKtext:
      "Users more easily move through a conversation with buttons.",
    BUTTONS_BLOCKbuttonText: "Add block with buttons",
    GOAL_BLOCKtitle: "Define a target block",
    GOAL_BLOCKtext:
      "Measuring the objectives of your campaigns will help you make better decisions.",
    GOAL_BLOCKbuttonText: "Define objective in your HSM",
    TWO_BLOCK_MINIMUMtitle: "Minimum create 2 blocks",
    TWO_BLOCK_MINIMUMtext:
      "Although everything can be included in the HSM, it is better to interact with your users.",
    TWO_BLOCK_MINIMUMbuttonText: "Add block with open answer",
    EMOJIStitle: "Use Emojis",
    EMOJIStext:
      "Emojis convey emotions and this makes your messages more relevant.",
    EMOJISbuttonText: "Add block with most used emojis",
    NOT_INCLUDED_ANSWERtitle: "Answer not included in options",
    NOT_INCLUDED_ANSWERtext:
      "If a user answers something other than the list of options/buttons, you can redirect them to a new block in the conversation or simply send them a custom message asking them to select one of the default options.",
    SHORT_TEXTtitle: "Use short texts",
    SHORT_TEXTtext:
      "We know that this does not apply to all cases, however, consider that people are going to spend a certain amount of time reading your messages, the more specific they are, the better.",
    automaticImprovementTitle: "Automatic improvement ⚡",
    automaticImprovementText:
      "We will add blocks and functionality to your flow automatically according to the following:",
    automaticImprovement1: "- Target Block in HSM",
    automaticImprovement2: "- Block with buttons",
    automaticImprovement3: "- Block with most used Emojis",
    automaticImprovementButtonText: "Accept and continue",
    questionEmojis:
      "These are the most used Emojis: (Copy and paste wherever you want) 😃 🙂 😋 😍 🤑 😎 🥳 🤫 🤔 🤗 😱 🤩 🤯 👋 👍 👌👇 👉 🙏 💪 ✨ 🔥 🍪 🚨 🚀 💰 🎉 📚 📍 🔍 🥁 👯 ‍️💎 ✅ ❗ 💯 📢 🔔 🕒 ⏰ 💲 🎁 💡 🛎 🎀",
    conversationQuality: "Conversation quality",
    score: "Points",
    automaticImprovement: "Automatic improvement",
    knowMoreTips: "Learn more tips",
    knowMore: "Learn more",
    normal: "Normal",
    advanced: "Advanced",
    recommendationLevel: "Depth of analysis",
    minimize: "Minimize",
    conversationQualityText1:
      "The quality of the conversation refers to the use of good practices in your campaigns.",
    conversationQualityText2:
      "At Treble.ai we analyze the data from the best campaigns that have been deployed and we are sure that these insights will make your conversations more effective.",
    evaluationTooBig:
      "Analysis not available for conversations of more than 100 blocks 😨",
    errorSavingConversation:
      "Error saving the conversation. Please contact support.",
    errorCreatingConversation:
      "Error creating the conversation. Please contact support.",
    loadingConversation: "Changes are being saved, wait a moment...",
    understood: "Understood",
    GOAL_BLOCKmustHave:
      "To save or overwrite this conversation you need to add a target block",
    publish: "Publish",
    publishNewConvTitle: "Publish new version of conversation",
    publishConvSub:
      "Before publishing a new version of the conversation consider the following implications:",
    publishItem1:
      "Any active sessions users have with this conversation will be closed if they are not talking to an agent.",
    publishItem2:
      "To see the results of previous versions in the statistics section, you must make sure that you select the correct version.",
    undo: "Undo",
    redo: "Redo",
    currentPublishedConv: "Published version:",
    synctool: "Changes saved",
    noDrafttool: "Not synced",
    notSynctool: "Not syncing",
    syncErrortool: "Check your connection",
    noPublishTool1:
      "For the conversation to be saved along with all the changes you make, you must ",
    noPublishTool2: " at least one version. 👌",
    noPublishedVersion: "No published version",
    noChangesApply:
      "You are viewing the published version of this conversation, so any changes you make here will not be saved.",
    continueEditing: "Exit to continue editing",
    publishedVersion: "Published Version View",
    firstLoad: "Conversation is loading, wait a moment...",
    changeVisualization: "Changing visualization, this may take a moment...",
    conversationsTemplatesModalText:
      "👉 Know the flows that generate the highest conversion 💥",
    conversationsTemplatesModalButton1: "Know flows",
    conversationsTemplatesModalButton2: "I'm not interested",
  },
  pr: {
    googleTitle: "Integração com planilhas do Google",
    googleDes:
      "Envie as respostas que seus usuários derem em tempo real para um documento do Planilhas Google.",
    sheeturl: "url de planilhas do google",
    intInfo: "Como funciona a integração?",
    clickHere: "Clique aqui",
    sheetMsg: "Enviar respostas em tempo real",
    loadingConv: "Estamos carregando sua conversa",
    read: "Ler",
    deliver: "Entregar",
    config: "Configurações de pergunta",
    questionType: "Tipo de pregunta",
    open: "Aberto",
    closed: "Fechadas",
    message: "Mensagem",
    altFlux: "Fluxo alternativo",
    hideOpt: "Esconder as respostas",
    variable: "Salvar resposta como variável",
    add: "Adicionar",
    openQuestion: "Com resposta aberta",
    closedQuestion: "Com lista de opções",
    withHsm: "Modelo de mensagem (HSM)",
    openQuestionD: "Ideal para coletar dados",
    closedQuestionD: "Caminhos diferentes para escolher",
    closedQuestionButtons: "Com lista de botões",
    closedQuestionButtonsD: "Até 3 botões de resposta rápida",
    closedQuestionList: "Com uma lista de opções",
    closedQuestionListD: "Até 10 opções de lista para seleção",
    humanChat: "Conversar com humanos",
    humanChatD: "Assuma o controle da conversa",
    connectConversation: "Conecte sua conversa a {{APPLICATION}}",
    linkConversation: "Conectar conversas",
    linkConversationD: "Pular para outra conversa",
    linkConversationLargeD:
      "Deseja levar seus usuários para outra conversa? Conecte conversas e crie novos caminhos para os seus usuários utilizando o bloco Conectar conversas.",
    abTesting: "Teste A/B",
    abTestingD: "Divida o fluxo por porcentagem",
    abTestingLargeD:
      "As menores alterações podem aumentar drasticamente a sua taxa de resposta. Com o bloco de teste A/B, você pode testar diferentes cópias ou até imagens para otimizar suas conversas.",
    conditionals: "Bloco condicional",
    conditionalsD: "Defina o caminho da conversa",
    conditionalsLargeD:
      "Envie aos seus usuários maneiras diferentes, dependendo dos dados ou dos parâmetros configuráveis.",
    wantBlock: "Deseja solicitar este bloco?",
    createAndUpdate: "Crie e atualize dados no {{CRM}}",
    connectTrebleWith: "Conecte treble.ai com {{APPLICATION}}",
    basicBlocks: "Blocos Básicos",
    advancedBlocks: "Blocos Avançados",
    blockType: "Tipo de bloco",
    integrations: "Integrações",
    sendEmail: "Enviar email",
    sendEmailD: "Para sua equipe ou usuários",
    sendEmailLargeD:
      "Tome uma ação rápida. Envie um e-mail para sua equipe ou para seus usuários a partir das respostas de suas conversas no treble.ai.",
    custom: "Personalizado",
    customD: "Deseja fazer outra integração?",
    withHsmD: "Mensagens aprovadas no Facebook",
    noHsm:
      "Verifique se a palavra está escrita corretamente ou tente alterar sua pesquisa",
    save: "Salvar como cópia",
    reWrite: "Substituir",
    create: "Criar",
    savebtn: "Salvar",
    convName: "Sem nome",
    noResults: "Sem resultados",
    continueAgents: "Continue em {{AGENTS}}",
    agentType: "Tipo de agente",
    helpdeskLargeD:
      "Crie tickets e permita que seus agentes controlem as conversas no {{HELPDESK}} a partir das respostas das suas conversas em treble.ai. Resolva rapidamente e forneça o melhor serviço aos seus usuários.",
    helpdeskEmail: "Seu {{HELPDESK}} email para permissões de administrador",
    helpdeskPhoneProperty:
      "Propriedade {{HELPDESK}} onde você armazena os telefones celulares de seus usuários",
    helpdeskAdminAccess:
      "Um administrador deve permitir o acesso do treble.ai a {{HELPDESK}}",
    installHelpdeskApp: "Instale o aplicativo treble.ai no {{HELPDESK}}",
    installZendeskApiKeyHelp: "Lá você deve inserir sua API key de treble.ai",
    installHere: "Instale aqui",
    allowAccess: "Permitir acesso",
    hubspotEmailD:
      "O email terá permissões de administrador dentro da integração HubSpot <> treble.ai para gerenciar outros agentes e tags",
    hubspotExtension: "Instale a extensão do Google Chrome em treble.ai",
    hubspotExtensionD:
      "Na página de configurações, você encontrará um link para instalar a extensão do Google Chrome e o código de ativação usado para vincular a extensão ao Treble. Cada pessoa que vai responder a mensagens do WhatsApp do HubSpot precisa fazer esse processo",
    goToTrebleSettings: "Vá para as configurações do Treble",
    crmLargeD:
      "Envie respostas treble.ai ao {{CRM}} para criar novos contatos ou atualizar seus detalhes. Você também pode implantar campanhas treble.ai em seus contatos do {{CRM}}",
    autoWorkflowsLargeD:
      "Conecte facilmente os dados coletados no treble.ai aos aplicativos que você usa no seu dia-a-dia com a rápida integração do {{APPLICATION}}.",
    hubspotReceiveEmail: "Quem vai receber essa conversa?",
    noStartFound: "Não conseguimos encontrar o início da conversa",
    cancel: "Cancelar",
    successRequestSent: "Solicitação enviada! Entraremos em contato em breve",
    requestIntegration: "Solicitar integração",
    requestNewIntegration: "Solicitar nova integração",
    whichApplication: "Qual aplicativo você gostaria de integrar?",
    applicationName: "Nome da Aplicação",
    useCase: "Caso de uso",
    requestNewIntegrationD:
      "Descreva brevemente o caso de uso que você gostaria de estar disponível com essa integração",
    wantIt: "Solicitar",
    completeField: "Por favor, preencha este campo",
    integrationWith: "Integração com {{APPLICATION}}",
    includeIntegration: "Deseja incluir esta integração?",
    hubspotModalTitle: "Conecte sua conta ao HubSpot",
    hubspotAccess:
      "Com essa integração, você autoriza o envio de conversas do HubSpot através do treble.ai e o acesso às informações de seus contatos com a mesma finalidade",
    account: "Conta",
    connect: "Conectar",
    successHubSpotConnect: "Você conectou o HubSpot com sucesso!",
    waitingHubSpotConnect: "Estamos conectando você ao HubSpot",
    input: "Pesquise ou crie uma nova variável",
    successRequest: "Solicitação enviada! Entraremos em contato em breve",
    sheetsLoad: "Verificando as permissões e o formato nas folhas do Google",
    sheetsSuccess: "Formato e permissões corretos!",
    sheetsNoPermissions:
      "Você não tem as permissões corretas nas folhas do Google",
    sheetsNoHeaders:
      "O arquivo deve conter country_code e cellphone em colunas separadas na primeira linha",
    sheetsInclude:
      "Você incluiu um arquivo de folhas do google! Lembre-se de ter o link público e com permissão do editor",
    sheetsProblem:
      "Encontramos um problema com seu arquivo de folhas do Google",
    atention: "Atenção!",
    helpdeskModalTitle: "Conecte sua conta com {{HELPDESK}}",
    helpdeskAccess:
      "Com esta integração você autoriza o envio de conversas do {{HELPDESK}} através do treble.ai e o acesso às informações dos seus contatos para o mesmo fim",
    helpdeskHost: "Domínio",
    successHelpdeskConnect:
      "Seu painel do {{HELPDESK}} agora está conectado a treble.ai!",
    helpdeskAPIKey: "Chave da API de um administrador",
    helpdeskCompanyId: "Identificador de sua empresa em {{HELPDESK}}",
    waitingHelpdeskConnect: "Estamos conectando você com o {{HELPDESK}}",
    noIntegration: "Parece que você já tem uma integração que não está com ",
    openQuestionType: "Abrir",
    closedQuestionType: "Fechadas",
    closedQuestionButtonsType: "Fechado com botões",
    closedQuestionListType: "Fechado na lista",
    equals: "é igual a",
    greater: "maior que",
    less: "menor que",
    greaterEqual: "maior ou igual a",
    lessEqual: "menor ou igual a",
    different: "diferente de",
    contains: "contém",
    notContains: "não contém",
    addCondition: "ADICIONE CONDIÇÃO",
    stablishConditions: "Estabelecer condições",
    configuration: "Configuração",
    name: "Nome",
    language: "Língua",
    spanish: "Espanhol",
    english: "Inglês",
    portuguese: "Português",
    french: "Francês",
    italian: "Italiano",
    limitMessagesAndTimer: "Limite de tempo e mensagem",
    noMessageLimit: "Ilimitado",
    messageLimit: "Número de mensagens",
    messageLimitDescription:
      "Limita o número de respostas que um usuário pode enviar antes de continuar o fluxo",
    exactNumber: "Número exato",
    timer: "Cronômetro",
    timerDescription:
      "Determine um tempo para o usuário responder antes de continuar com o fluxo",
    seconds: "Segundos",
    minutes: "Minutos",
    saveOnVariableDescription:
      "Armazene a resposta do usuário como uma variável de acordo com o tipo de mensagem (texto, imagem, documento, etc.)",
    typeOfVariable: "Tipo de resposta",
    nameOfVariable: "Nome variável",
    allVarTypes: "Todos os tipos",
    textVarType: "Texto",
    imageVarType: "Imagem",
    videoVarType: "Vídeo",
    audioVarType: "Áudio",
    documentVarType: "Arquivo",
    locationVarType: "Localização",
    stickerVarType: "Sticker",
    numericVarType: "Número",
    emailVarType: "Email",
    zipcodeVarType: "Código postal",
    contactsVarType: "Contato",
    noStart: "Não é possível encontrar um iniciador de conversa",
    selectPoll: "Selecione a conversa",
    redirectPollD:
      "Redirecione seus usuários para outras conversas, vinculando fluxos dentro do mesmo criador",
    searchPoll: "Pesquise sua conversa por nome ou ID",
    new: "NOVO",
    noPollRed: "Uma das conversas redirecionadas foi excluída.",
    autoMsgPA: "Você ainda está aí?",
    autoMsg: "Nova tentativa automática de mensagem",
    autoTime: "tempo de repetição automática",
    autoTitle: "Repetição automática",
    customAns: "Personalize suas respostas como um opt-out",
    optWeb: "Definir um webhook opt-out",
    sheetsVariable: "Variável de mensagem de entrada",
    sheetsVariablePH: "Nome da variável na sua sheet",
    alternateFlowError:
      "Opa! Existem blocos que estão conectados de tal forma que você enviará infinitas mensagens se eles não responderem. Verifique sua conversa",
    nodeErrors:
      "Há algo errado com as perguntas destacadas. Revise estas perguntas",
    helpdeskAction: "Ação no CRM",
    helpdeskActionD: "Salvar valores no Hubspot",
    customCondition: "⚙️ Condição personalizada",
    timeCondition: "⏰ Condição horária",
    timezone: "Fuso horário",
    timezonePH: "Escolha um fuso horário",
    timezoneSearch: "Encontrar um fuso horário",
    to: "para",
    between: "entre",
    selectTimezone: "Defina o fuso horário na seção de configuração",
    overwriteConfirmationTitle: "Substituir conversa?",
    overwriteConfirmation1: "Sobrescrever a conversa tem algumas implicações",
    overwriteConfirmation2:
      "Todas as sessões ativas que os usuários tiverem com esta conversa serão encerradas se eles não estiverem falando com um agente",
    overwriteConfirmation3:
      "Uma nova versão desta conversa será criada. Se você quiser verificar os resultados anteriores na seção de estatísticas, certifique-se de selecionar a versão correta",
    askTwilioListContentSid:
      "Por favor insira o Content Sid da sua mensagem do tipo twilio/list-picker.",
    helpdeskTicket: "Criação de bilhete",
    helpdeskTicketD: "Criar bilhetes no Hubspot",
    NoResultsFound: "Oops, sem resultados. 👀 Tente outro nome",
    hubspotV1Error: "Exclua todos os nós do HubSpot V1 antes de continuar",
    hubspotV1Deprecated: "O HubSpot V1 não é mais compatível",
    hubspotV1DeprecatedD:
      "A versão 1 do agente HubSpot não é mais compatível com agudos. Remova este nó se desejar salvar esta conversa",
    modalErrorTitle: "Erro ao conectar ao hubspot",
    modalErrorBody:
      "Falha ao sincronizar recursos e variáveis ​​do HubSpot nesta conversa (isso não afetará sua operação). Editar e adicionar ações do HubSpot requer um recarregamento da página",
    continueToEditor: "Continuar para o editor",
    tryAgain: "Tente novamente",
    hsmPH: "Pesquisar pelo nome do modelo HSM...",
    hsmPaused: "HSM pausado",
    hsmPausedText:
      "Atualmente, este modelo HSM atingiu a classificação de qualidade mais baixa (vermelho) e está desabilitado. Meta pausa automaticamente todos os modelos que atingiram esta instância para proteger a classificação de qualidade do número de telefone. Para mais informações, você pode acessar:",
    optoutWarningTitle: "Você está prestes a usar uma opção de desativação",
    optoutWarningText:
      "Lembre-se de que, ao colocar uma opção como optout, você concorda que não poderá contatar todos os usuários que a selecionarem. (Treble.ai também não poderá contatá-los)",
    optoutWarningButton: "Aceito os termos da opção optout",
    optoutWarningheader: "🚨 😱 ⚠️",
    tipsMenuTitle: "Biblioteca de dicas",
    curiositytitle: "🤔 Desperte a curiosidade",
    optouttitle: "🥶 Use a opção de opt-out",
    imagestitle: "👀 Utilize imagens",
    shorttitle: "👌 Crie fluxos curtos",
    tonetitle: "😁 Utilize o tom de voz da sua marca",
    optionstitle: "📗 Utilize blocos de mensagens com opções",
    targettitle: "🎯 Insira seu Bloco de Objetivos no início da conversa",
    abtestingtitle: "😉 Faça testes A/B",
    curiositymainInfo:
      "Você pode aumentar a taxa de resposta despertando curiosidade dos seus usuários.",
    optoutmainInfo:
      "Ativando essa opção, você permite que seus usuários escolham se querem ou não continuar recebendo suas mensagens.",
    imagesmainInfo:
      "Inserir imagens ajuda a tornar o conteúdo das suas mensagens mais atrativo, mas sem exageros! Usar imagens demais em suas conversas pode acabar confundindo seu usuário. Equilíbrio é tudo!",
    shortmainInfo:
      "Sabemos que isso não se aplica a todos os casos, mas os fluxos curtos podem te ajudar a tornar a conversa com seus usuários mais fácil e dinâmica.\n\nUm fluxo curto possui no máximo 10 blocos de mensagens.",
    tonemainInfo:
      "Definir e utilizar o tom de voz da sua marca nas conversas te ajuda a se conectar melhor com seus usuários.\n\nColocar o tom de voz em prática de maneira efetiva faz com que seus usuários engajem muito mais com o conteúdo que você envia.",
    optionsmainInfo:
      "É mais provável que os usuários continuem no fluxo se você facilitar a tomada de decisão mostrando uma lista de opções de resposta.",
    targetmainInfo:
      "Sabemos que isso não se aplica a todos os casos, mas colocar o Bloco de Objetivos no início do fluxo aumenta as chances de que ele seja alcançado.",
    abtestingmainInfo:
      "Uma boa prática é utilizar o bloco de testes A/B. O benefício principal dessa funcionalidade é te ajudar a conhecer as preferências dos seus usuários para que você possa utilizar essas informações para otimizar suas campanhas.\n\nEntender os conteúdos e textos que funcionam melhor para sua audiência é fundamental para melhorar a qualidade de suas próximas campanhas.",
    example: "Exemplo:",
    benefits: "Benefícios:",
    optoutOption1:
      "Você mantém sua base de usuários atualizada e envia mensagens somente aos usuários que realmente querem receber seu conteúdo, realizando campanhas muito mais eficazes.",
    optoutOption2:
      "Sua linha do WhatsApp fica livre do risco de ser bloqueada ou denunciada por usuários que não querem receber seu conteúdo.",
    howToActivate: "Como ativar esta opção?",
    BUTTONS_BLOCKtitle: "Utilize blocos de mensagens com botões",
    BUTTONS_BLOCKtext:
      "Os usuários passam mais facilmente por uma conversa com botões.",
    BUTTONS_BLOCKbuttonText: "Adicionar bloco com botões",
    GOAL_BLOCKtitle: "Insira um Bloco de Objetivos na campanha",
    GOAL_BLOCKtext:
      "Medir os objetivos de suas campanhas ajudará você a tomar melhores decisões.",
    GOAL_BLOCKbuttonText: "Defina o objetivo em seu HSM",
    TWO_BLOCK_MINIMUMtitle: "Crie pelo menos 2 blocos de mensagens",
    TWO_BLOCK_MINIMUMtext:
      "Embora tudo possa ser incluído no HSM, é melhor interagir com seus usuários.",
    TWO_BLOCK_MINIMUMbuttonText: "Adicionar bloco com resposta aberta",
    EMOJIStitle: "Utilize emojis",
    EMOJIStext:
      "Os emojis transmitem emoções e isso torna suas mensagens mais relevantes.",
    EMOJISbuttonText: "Adicionar bloco com os emojis mais usados",
    NOT_INCLUDED_ANSWERtitle: "Insira a opção de resposta não incluída",
    NOT_INCLUDED_ANSWERtext:
      "Se um usuário responder algo diferente da lista de opções/botões, você pode redirecioná-lo para um novo bloco na conversa ou simplesmente enviar uma mensagem personalizada solicitando que ele selecione uma das opções padrão.",
    SHORT_TEXTtitle: "Utilize textos curtos",
    SHORT_TEXTtext:
      "Sabemos que isso não se aplica a todos os casos, porém, considere que as pessoas vão gastar um certo tempo lendo suas mensagens, quanto mais específicas forem, melhor.",
    automaticImprovementTitle: "Melhoria automática ⚡",
    automaticImprovementText:
      "Adicionaremos blocos e funcionalidades ao seu fluxo automaticamente de acordo com o seguinte:",
    automaticImprovement1: "- Bloco de destino no HSM",
    automaticImprovement2: "- Bloco com botões",
    automaticImprovement3: "- Bloco com Emojis mais usados",
    automaticImprovementButtonText: "Aceptar y continuar",
    questionEmojis:
      "Estes são os Emojis mais usados: (Copie e cole onde quiser) 😃 🙂 😋 😍 🤑 😎 🥳 🤫 🤔 🤗 😱 🤩 🤯 👋 👍 👌👇 👉 🙏 💪 ✨ 🔥 🍪 🚨 🚀 💰 🎉 📚 📍 🔍 🥁 👯 ‍️💎 ✅ ❗ 💯 📢 🔔 🕒 ⏰ 💲 🎁 💡 🛎 🎀",
    conversationQuality: "Qualidade da conversa",
    score: "Pontos",
    automaticImprovement: "Melhoria automática",
    knowMoreTips: "Saiba mais dicas",
    knowMore: "Saber mais",
    normal: "Normal",
    advanced: "Avançado",
    recommendationLevel: "Profundidade de análise",
    minimize: "Minimizar",
    conversationQualityText1:
      "A qualidade da conversa depende do uso das boas práticas em suas campanhas.",
    conversationQualityText2:
      "Na Treble.ai, analisamos os dados das suas melhores campanhas e temos a certeza de que esses insights tornarão suas conversas mais eficazes.",
    evaluationTooBig:
      "Análise não disponível para conversas de mais de 100 blocos 😨",
    errorSavingConversation:
      "Erro ao salvar a conversa. Entre em contato com o suporte.",
    errorCreatingConversation:
      "Erro ao criar a conversa. Entre em contato com o suporte.",
    loadingConversation:
      "As alterações estão sendo salvas, aguarde um momento...",
    understood: "Entendido",
    GOAL_BLOCKmustHave:
      "Para salvar ou substituir esta conversa, você precisa adicionar um bloco de destino",
    publish: "Publicar",
    publishNewConvTitle: "Publicar nova versão da conversa",
    publishConvSub:
      "Antes de publicar uma nova versão da conversa, considere as seguintes implicações:",
    publishItem1:
      "Quaisquer sessões ativas que os usuários tenham com esta conversa serão encerradas se não estiverem conversando com um agente.",
    publishItem2:
      "Para ver os resultados das versões anteriores na seção de estatísticas, certifique-se de selecionar a versão correta.",
    undo: "Desfazer",
    redo: "Refazer",
    currentPublishedConv: "Versão publicada:",
    synctool: "Alterações salvas",
    noDrafttool: "Não sincronizado",
    notSynctool: "Não sincronizando",
    syncErrortool: "Verifique sua conexão",
    noPublishTool1:
      "Para que a conversa seja salva junto com todas as alterações que você fizer, você deve ",
    noPublishTool2: "pelo menos uma versão. 👌",
    noPublishedVersion: "Nenhuma versão publicada",
    noChangesApply:
      "Você está visualizando a versão publicada desta conversa, então qualquer alteração que você fizer aqui não será salva.",
    continueEditing: "Sair para continuar editando",
    publishVersion: "Visualização da versão publicada",
    firstLoad: "A conversa está carregando, aguarde um momento...",
    changeVisualization:
      "Mudando a visualização, isso pode demorar um pouco...",
      conversationsTemplatesModalText:
        "👉 Conheça os fluxos que geram maior conversão 💥",
      conversationsTemplatesModalButton1: "Conheça os fluxos",
      conversationsTemplatesModalButton2: "Não me interessa",
  },
};
