module.exports = {
  es: {
    write: "Escribe aquí...",
    timeout: "Después de {{min}} minutos",
    config: "Configuración",
    duplicate: "Duplicar",
    delete: "Eliminar",
    conecctions: "Conexiones",
    tooltipMsg1:
      "Selecciona un bloque y usa el nodo circular para arrastrar la conexion a otro bloque",
    addBlock: "para agregar bloque abajo",
    openMenu: "para abrir menú",
    altFlux: "Flujo alterno",
    altFluxMsg:
      "Envía un mensaje a tu usuario si después de x tiempo no ha respondido",
    defaultAnswer: "Respuesta no incluida en opciones",
    continueHubSpot: "Continuar en HubSpot",
    drag: "Arrastra",
    dragAction: "para mover",
    continueFreshdesk: "Continuar en Freshdesk",
    continueKustomer: "Continuar en Kustomer",
    continueCustom: "Continuar en Custom",
    continueIntercom: "Continuar en Intercom",
    condition: "Condiciones",
    if: "Si",
    gallery: "Galería",
    documents: "Documentos",
    location: "Ubicación",
    save: "Guardar",
    cancel: "Cancelar",
    address: "Dirección",
    locationVariable:
      "Para que esto funcione necesitas escribir una variable válida con el formato {{VARIABLE}}",
    locationVariableTitle: "Tener en cuenta",
    actions: "ACCIONES",
    buttons: "BOTONES",
    list: "LISTA",
    redirectToPoll: "Ir a conversación",
    selectPoll: "Elige una conversación",
    variable: "Variable",
    variableFile: "Archivo variable",
    variableFilePlaceholder: "Nombre de la variable que contendrá el archivo",
    probabilities: "Probabilidades",
    abTest: "Pruebas A/B",
    helpdeskAction: "Acción en CRM",
    newAction: "Crear nueva acción",
    place: "Colocar",
    replaceWith: "Reemplazar con",
    add: "Agregar",
    remove: "Eliminar",
    inProperty: "En la propiedad",
    selectProperty: "Selecciona una propiedad de contacto",
    selectPropertyPH: "Selecciona una propiedad...",
    searchByNamePH: "Buscar por nombre",
    inputPH: "Escribe aquí...",
    selectValuePH: "Selecciona una de las opciones...",
    selectMultiplePH: "Selecciona una o varias opciones...",
    replace: "Reemplazar",
    saveAsText: "Guardar como texto",
    saveAsNumber: "Guardar como número",
    saveAsOption: "Escoge una de las siguientes opciones",
    saveAsMultipleOption: "Agrega, elimina o reemplaza múltiples opciones",
    saveAt: "La información se guardará en",
    saveAndContinue: "Guardar y continuar",
    helpdeskActionError1: "Completa el paso 1 para poder avanzar",
    helpdeskActionError2: "Completa el paso 2 para poder avanzar",
    timeCondition: "Condición horaria",
    to: "hasta",
    helpdeskTicket: "Ticket en",
    createHelpdeskTicket: "Crear nuevo ticket",
    helpdeskTicketRequiredFields:
      "Completa los campos requeridos para poder avanzar",
    invalidFile: "Tipo de archivo invalido",
  },
  en: {
    continueCustom: "Continue in Custom",
    write: "Write here...",
    timeout: "After {{min}} minutes",
    config: "Configuration",
    duplicate: "Duplicate",
    delete: "Delete",
    conecctions: "Connections",
    tooltipMsg1:
      "Select a block and use the circular node to drag the connection to another block",
    addBlock: "to add block below",
    openMenu: "to open menu",
    altFlux: "Alternate flow",
    altFluxMsg: "Send a message to your user if after x time has not responded",
    defaultAnswer: "Answer not included in options",
    continueHubSpot: "Continue on HubSpot",
    drag: "Drag",
    dragAction: "to move",
    continueFreshdesk: "Continue on Freshdesk",
    continueKustomer: "Continue on Kustomer",
    continueIntercom: "Continue on Intercom",
    condition: "Conditions",
    if: "If",
    gallery: "Gallery",
    documents: "Documents",
    location: "Location",
    save: "Save",
    cancel: "Cancel",
    address: "Address",
    locationVariable:
      "For this to work you need to type a valid variable with the format {{VARIABLE}}",
    locationVariableTitle: "Take into account",
    actions: "ACTIONS",
    buttons: "BUTTONS",
    list: "LIST",
    redirectToPoll: "Go to conversation",
    selectPoll: "Select a conversation",
    variable: "Variable",
    variableFile: "Variable File",
    variableFilePlaceholder: "Variable name that contains the file",
    probabilities: "Probabilities",
    abTest: "A/B Test",
    helpdeskAction: "CRM Action",
    newAction: "Create new action",
    place: "Set",
    replaceWith: "Replace with",
    add: "Add",
    remove: "Remove",
    inProperty: "On property",
    selectProperty: "Select a contact property",
    selectPropertyPH: "Select a property...",
    searchByNamePH: "Search by name",
    inputPH: "Write here...",
    selectValuePH: "Select one of the options...",
    selectMultiplePH: "Select one or more options...",
    replace: "Replace",
    saveAsText: "Save as text",
    saveAsNumber: "Save as number",
    saveAsOption: "Choose one of the following options",
    saveAsMultipleOption: "Add, remove or replace multiple options",
    saveAt: "The information will be stored in",
    saveAndContinue: "Save and continue",
    helpdeskActionError1: "Complete step 1 to be able to advance",
    helpdeskActionError2: "Complete step 2 to be able to advance",
    timeCondition: "Time condition",
    to: "to",
    helpdeskTicket: "Ticket in",
    createHelpdeskTicket: "Create new ticket",
    helpdeskTicketRequiredFields:
      "Complete the required fields to be able to advance",
    invalidFile: "Invalid file type",
  },
  pr: {
    continueCustom: "Continue no Custom",
    write: "Escreva aqui...",
    timeout: "Após {{min}} minutos",
    config: "Configuração",
    duplicate: "Em dobro",
    delete: "Retirar",
    conecctions: "Conexões",
    tooltipMsg1:
      "Selecione um bloco e use o nó circular para arrastar a conexão para outro bloco",
    addBlock: "para adicionar o bloco abaixo ",
    openMenu: "para abrir o menu",
    altFlux: "Fluxo alternativo",
    altFluxMsg:
      "Envie uma mensagem ao seu usuário se após o x tempo não responder",
    defaultAnswer: "Resposta não incluída nas opções",
    continueHubSpot: "Continue no HubSpot",
    drag: "Arraste",
    dragAction: "para mover",
    continueFreshdesk: "Continue no Freshdesk",
    continueKustomer: "Continue no Kustomer",
    continueIntercom: "Continue no Intercom",
    condition: "Condições",
    if: "E se",
    gallery: "Galeria",
    documents: "Documentos",
    location: "Localização",
    save: "Salve",
    cancel: "Cancelar",
    address: "Direção",
    locationVariable:
      "Para que isso funcione, você precisa digitar uma variável válida com o formato {{VARIABLE}}",
    locationVariableTitle: "Ter em conta",
    actions: "AÇÕES",
    buttons: "BOTÕES",
    list: "LISTA",
    redirectToPoll: "Ir para a conversa",
    selectPoll: "Escolha uma conversa",
    variable: "Variável",
    variableFile: "Arquivo variável",
    variableFilePlaceholder: "Nome da variável que contendrá el archivo",
    probabilities: "Probabilidades",
    abTest: "Teste A/B",
    helpdeskAction: "Ação no CRM",
    newAction: "Criar nova ação",
    place: "Definir",
    replaceWith: "Reemplazar con",
    add: "Adicionar",
    remove: "Remover",
    inProperty: "Na propriedade",
    selectProperty: "Selecione uma propriedade de contato",
    selectPropertyPH: "Selecione uma propiedade...",
    searchByNamePH: "Procura por nome",
    inputPH: "Escreva aqui...",
    selectValuePH: "Selecione uma das opções...",
    selectMultiplePH: "Selecione uma ou mais opções...",
    replace: "Reemplazar",
    saveAsText: "Salvar como texto",
    saveAsNumber: "Salvar como número",
    saveAsOption: "Escolha uma das seguintes opções",
    saveAsMultipleOption: "Adicionar, remover ou substituir várias opções",
    saveAt: "As informações serão armazenadas em",
    saveAndContinue: "Salve e continue",
    helpdeskActionError1: "Complete o passo 1 para poder avançar",
    helpdeskActionError2: "Complete o passo 2 para poder avançar",
    timeCondition: "Condição horária",
    to: "às",
    helpdeskTicket: "Bilhete em",
    createHelpdeskTicket: "Criar novo bilhete",
    helpdeskTicketRequiredFields:
      "Preencha os campos obrigatórios para poder avançar",
    invalidFile: "Tipo de arquivo inválido",
  },
};
